ARG PG_MAJOR=17
ARG DEBIAN_CODENAME=trixie

FROM postgres:$PG_MAJOR-$DEBIAN_CODENAME

ADD https://github.com/pgvector/pgvector.git#v0.8.0 /tmp/pgvector

RUN <<EORUN
#!/bin/bash -ex
apt-get update
apt-mark hold locales
apt-get install -y --no-install-recommends build-essential postgresql-server-dev-$PG_MAJOR

cd /tmp/pgvector
make clean
make OPTFLAGS=""
make install
mkdir /usr/share/doc/pgvector
cp LICENSE README.md /usr/share/doc/pgvector
rm -r /tmp/pgvector

apt-get remove -y build-essential postgresql-server-dev-$PG_MAJOR
apt-get autoremove -y
apt-mark unhold locales
rm -rf /var/lib/apt/lists/*
EORUN
