name: build postgres

on:
  push:
    branches: ["master"]
    paths:
      - postgres/**
      - .github/workflows/postgres.yml

jobs:
  build-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - postgres: 16
          - postgres: 17
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./postgres
          push: true
          build-args: |
            PG_MAJOR=${{ matrix.postgres }}
            DEBIAN_CODENAME=trixie
          tags: ghcr.io/${{ github.repository }}/postgres:${{ matrix.postgres }},ghcr.io/${{ github.repository }}/postgres:${{ matrix.postgres }}-${{ github.sha }}
